name: nakama
data_dir: "./data/"

logger:
  stdout: false
  level: "INFO"
  file: "/nakama/data/logfile.log"

session:
  token_expiry_sec: 7200

socket:
  server_key: "defaultkey"
  port: 7350

database:
  address: ["postgres:localdb@localhost:5432/nakama"]

runtime:
  env:
    - "NODE_ENV=development"
  path: "/nakama/data/modules"
  http_key: "defaulthttpkey"